### ISSUE TITLE
postgresql.conf の archive_mode をoff にする

### ISSUE THREAD

**Issue by khattori** [fixpoint/ke2-docker#23]
setup_pgpool.sh 内で archive_mode を on にしているが、そうすると、/var/lib/pgsql/archivedir に WAL が溜まっていき、DISK領域を圧迫する。
PITR（ポイントインタイムリカバリ）を行わないのであれば、この設定は不要なので、デフォルトのセットアップでは、 archive_mode を off （postgresql のデフォルト）のままにしておく。

**Comment by tichi73** [comment]
@khattori 
archive_mode=off にすると、pgpool によるフェイルオーバが正常に機能していないように見受けられるのですが、再現するか確認してみていただけますか。
https://fixpoint.slack.com/archives/C01163D6JAC/p1722397148145879
